// array d can be edited to edit the HTML selector of projects
// this file created the projects selector
var d = [
  "Select a project here :)",
  "Ace [graduated]",
  "APISIX [graduated]",
  "AWF [retired]",
  "Abdera [graduated]",
  "Accumulo [graduated]",
  "ActiveMQ [graduated]",
  "Agila [retired]",
  "Airavata [graduated]",
  "Airflow [graduated]",
  "Allura [graduated]",
  "Alois [retired]",
  "Amaterasu [retired]",
  "Ambari [graduated]",
  "Amber [graduated]",
  "Any23 [graduated]",
  "Apex [graduated]",
  "AriaTosca [retired]",
  "Aries [graduated]",
  "AsterixDB [graduated]",
  "Atlas [graduated]",
  "Aurora [graduated]",
  "BatchEE [graduated]",
  "Beam [graduated]",
  "Bean Validation [graduated]",
  "Beehive [graduated]",
  "Bigtop [graduated]",
  "Bloodhound [graduated]",
  "Bluesky [retired]",
  "Blur [retired]",
  "Brooklyn [graduated]",
  "Buildr [graduated]",
  "CXF [graduated]",
  "Calcite [graduated]",
  "CarbonData [graduated]",
  "Cassandra [graduated]",
  "Cayenne [graduated]",
  "Celix [graduated]",
  "Chemistry [graduated]",
  "Chukwa [graduated]",
  "Clerezza [graduated]",
  "Click [graduated]",
  "Climate Model Diagnostic Analyzer [retired]",
  "CloudStack [graduated]",
  "CommonsRDF [graduated]",
  "Composer [retired]",
  "Concerted [retired]",
  "Cordova [graduated]",
  "Corinthia [retired]",
  "Cotton [retired]",
  "CouchDB [graduated]",
  "Crunch [graduated]",
  "Curator [graduated]",
  "Daffodil [graduated]",
  "DataFu [graduated]",
  "DataSketches [graduated]",
  "DeltaSpike [graduated]",
  "Deltacloud [graduated]",
  "Depot [retired]",
  "Derby [graduated]",
  "DeviceMap [graduated]",
  "DirectMemory [graduated]",
  "Directory [graduated]",
  "DistributedLog [graduated]",
  "DolphinScheduler [graduated]",
  "Drill [graduated]",
  "Droids [retired]",
  "Druid [graduated]",
  "Dubbo [graduated]",
  "ECharts [graduated]",
  "ESME [graduated]",
  "Eagle [graduated]",
  "EasyAnt [graduated]",
  "Edgent [retired]",
  "Empire-db [graduated]",
  "Etch [graduated]",
  "Falcon [graduated]",
  "Felix [graduated]",
  "Fineract [graduated]",
  "Flex [graduated]",
  "Flink [graduated]",
  "Flume [graduated]",
  "Fluo [graduated]",
  "FreeMarker [graduated]",
  "FtpServer [graduated]",
  "Gearpump [retired]",
  "Geode [graduated]",
  "Geronimo [graduated]",
  "Giraph [graduated]",
  "Gobblin [graduated]",
  "Gora [graduated]",
  "Gossip [retired]",
  "Graffito [retired]",
  "Griffin [graduated]",
  "Groovy [graduated]",
  "Guacamole [graduated]",
  "HAWQ [graduated]",
  "HCatalog [graduated]",
  "HISE [retired]",
  "HORN [retired]",
  "HTrace [retired]",
  "Hadoop Development Tools (HDT) [retired]",
  "Hama [graduated]",
  "Harmony [graduated]",
  "Helix [graduated]",
  "Heraldry [retired]",
  "Hermes [graduated]",
  "Hudi [graduated]",
  "Iceberg [graduated]",
  "Ignite [graduated]",
  "Impala [graduated]",
  "Imperius [retired]",
  "IoTDB [graduated]",
  "Isis [graduated]",
  "Ivy [graduated]",
  "JDO [graduated]",
  "JSPWiki [graduated]",
  "Jackrabbit [graduated]",
  "Jena [graduated]",
  "Johnzon [graduated]",
  "Joshua [graduated]",
  "JuiCE [retired]",
  "Juneau [graduated]",
  "Kabuki [retired]",
  "Kafka [graduated]",
  "Kalumet [retired]",
  "Kato [retired]",
  "Kitty [retired]",
  "Knox [graduated]",
  "Kudu [graduated]",
  "Kylin [graduated]",
  "Lens [graduated]",
  "Lenya [graduated]",
  "Libcloud [graduated]",
  "Lokahi [retired]",
  "Lucene.NET [graduated]",
  "Lucy [graduated]",
  "MADlib [graduated]",
  "MRQL [retired]",
  "MRUnit [graduated]",
  "ManifoldCF [graduated]",
  "Marmotta [graduated]",
  "Mesos [graduated]",
  "MetaModel [graduated]",
  "Metron [graduated]",
  "Mnemonic [graduated]",
  "Muse [graduated]",
  "Mynewt [graduated]",
  "Myriad [retired]",
  "NMaven [retired]",
  "NPanday [retired]",
  "NetBeans [graduated]",
  "NiFi [graduated]",
  "Nutch [graduated]",
  "Nuvem [graduated]",
  "ODF Toolkit [retired]",
  "OFBiz [graduated]",
  "OGNL [graduated]",
  "OODT [graduated]",
  "Ode [graduated]",
  "Olingo [graduated]",
  "Olio [retired]",
  "Omid [graduated]",
  "Onami [graduated]",
  "Oozie [graduated]",
  "Open Climate Workbench [graduated]",
  "OpenAz [retired]",
  "OpenJPA [graduated]",
  "OpenNLP [graduated]",
  "OpenOffice.org [graduated]",
  "OpenWebBeans [graduated]",
  "OpenWhisk [graduated]",
  "Openmeetings [graduated]",
  "PDFBox [graduated]",
  "PLC4X [graduated]",
  "Parquet [graduated]",
  "Phoenix [graduated]",
  "PhotArk [retired]",
  "Pig [graduated]",
  "Pinot [graduated]",
  "Pirk [retired]",
  "Pivot [graduated]",
  "PredictionIO [graduated]",
  "Provisionr [retired]",
  "Pulsar [graduated]",
  "Qpid [graduated]",
  "Quickstep [retired]",
  "RCF [retired]",
  "REEF [graduated]",
  "Ranger [graduated]",
  "Ratis [graduated]",
  "Rave [graduated]",
  "Ripple [retired]",
  "River [graduated]",
  "RocketMQ [graduated]",
  "Roller [graduated]",
  "Rya [graduated]",
  "S2Graph [retired]",
  "S4 [retired]",
  "SAMOA [retired]",
  "SINGA [graduated]",
  "SIS [graduated]",
  "Samza [graduated]",
  "Sanselan [graduated]",
  "Sentry [graduated]",
  "ServiceComb [graduated]",
  "ServiceMix [graduated]",
  "ShardingSphere [graduated]",
  "Shindig [graduated]",
  "Shiro [graduated]",
  "Sirona [retired]",
  "SkyWalking [graduated]",
  "Slider [retired]",
  "Sling [graduated]",
  "SocialSite [retired]",
  "Solr [graduated]",
  "SpamAssassin [graduated]",
  "Spark [graduated]",
  "Sqoop [graduated]",
  "Stanbol [graduated]",
  "Stonehenge [retired]",
  "Storm [graduated]",
  "Stratos [graduated]",
  "Streams [graduated]",
  "Subversion [graduated]",
  "Superset [graduated]",
  "Synapse [graduated]",
  "Syncope [graduated]",
  "SystemML [graduated]",
  "TVM [graduated]",
  "Tajo [graduated]",
  "Tamaya [retired]",
  "Tapestry [graduated]",
  "Tashi [retired]",
  "Taverna [retired]",
  "Tephra [graduated]",
  "Tez [graduated]",
  "Thrift [graduated]",
  "Tika [graduated]",
  "TinkerPop [graduated]",
  "Tobago [graduated]",
  "Traffic Control [graduated]",
  "Traffic Server [graduated]",
  "Trafodion [graduated]",
  "Trinidad [graduated]",
  "TripleSoup [retired]",
  "Tuscany [graduated]",
  "Twill [graduated]",
  "UIMA [graduated]",
  "Unomi [graduated]",
  "Usergrid [graduated]",
  "VCL [graduated]",
  "VXQuery [graduated]",
  "Warble [retired]",
  "Wave [retired]",
  "WebWork 2 [graduated]",
  "Weex [retired]",
  "Whirr [graduated]",
  "Wicket [graduated]",
  "Wink [graduated]",
  "Wookie [graduated]",
  "XAP [retired]",
  "XMLBeans [graduated]",
  "Yoko [retired]",
  "Zeppelin [graduated]",
  "Zeta Components [retired]",
  "Zipkin [retired]",
  "cTAKES [graduated]",
  "iBATIS [graduated]",
  "iota [retired]",
  "jUDDI [graduated]",
  "jclouds [graduated]",
  "mod_ftp [graduated]",
  "stdcxx [graduated]",
];

var select = document.getElementById("txt_ide");
//  for every element in the array we create options for the HTML select tag
for (var i = 0; i < d.length; i++) {
  var opt = document.createElement("option");
  opt.textContent = d[i];
  select.appendChild(opt);
}

// if ($("#chk").is(":checked")) console.log("checked");
// else {
//   console.log("unchecked");
// }

// we have the function for the open parallel window button
//  here we need to edit in case we want the link to point elsewhere
function openWin() {
  window.open("https://anirudhsuresh.github.io/APEX/");
}
